version: '3'
services:
  mongodb:
    image: mongo
    ports: 
      - "27018:27017"
  web-app:
    build: ./web_app
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
  machine_learning_client:
    build: ./machine_learning_client
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
