name: Python Application Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust the Python version as necessary

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Assuming pytest is used for running the tests
        # If there are other dependencies, install them here or use a requirements.txt file
        # pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest test_app.py  # Adjust the command according to your test runner
