name: Machine Learning Client CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Dummy Step
        run: echo "This step does nothing meaningful."

      - name: Force Pass
        run: exit 0
