name: machine_learning_client CI / CD
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd machine_learning_client
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv --python ${{ matrix.python-version }}
          pipenv install --dev  # Install all dependencies and dev dependencies from Pipfile
          pipenv install pytest  # Explicitly install pytest
      - name: Run tests
        run: |
          pipenv run pytest  # Run tests with pytest