name: web_app CI / CD
on:
  pull_request:
    branches:
      - main

jobs:
  always_pass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Assuming you are using Python 3.9

      - name: Install dependencies and run tests
        run: |
          echo "Installing dependencies..."
          pip install pytest # Assuming pytest is used for tests
          echo "Running tests..."
          pytest || true # The '|| true' ensures this command always succeeds