name: Python Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Change this to whatever Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Or your specific test runner if different
        pip install -r requirements.txt  # Assumes you have a requirements.txt

    - name: Run tests
      run: |
        pytest test_app.py  # Replace pytest with your test command if different
